Repository pytroll/pyresample, pull requests merged in 2018-12, with the labels that each got.

#145 Refactor and deprecate geometry "*_dask" methods
  appveyor.yml
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: enhancement

#149 Added another possible error in parse_area_file
  pyresample/utils.py
Labels: PCW

#150 Switch to versioneer
  .gitattributes
  MANIFEST.in
  RELEASING.md
  codecov.yml
  docs/source/conf.py
  pyresample/__init__.py
  pyresample/version.py
  setup.cfg
  setup.py
  versioneer.py
Labels: PCW, enhancement
