Repository pytroll/pyresample, pull requests merged in 2019-12, with the labels that each got.

#236 Fix compatibility with pyproj 2.4.2
  pyresample/ewa/__init__.py
  pyresample/ewa/_ll2cr.c
  pyresample/ewa/_ll2cr.pyx
  pyresample/geometry.py
  pyresample/grid.py
  pyresample/kd_tree.py
  pyresample/spherical_geometry.py
  pyresample/test/test_geometry.py
  pyresample/test/test_spherical.py
  pyresample/test/test_utils.py
  pyresample/test/utils.py
Labels: bug

#238 Update load_area docstring to mention that multiple files are allowed
  pyresample/area_config.py
Labels: documentation

#227 Fix EWA resampling hanging when geolocation had a lot of NaNs
  pyresample/ewa/_fornav.cpp
  pyresample/ewa/_fornav_templates.cpp
  pyresample/test/test_ewa_fornav.py
Labels: bug

#241 update grid
  docs/source/grid.rst
Labels: bug, documentation

#243 Respect dtype when get_lonlats provide dask array
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: bug

#191 Implement gradient search resampling method
  pyresample/geometry.py
  pyresample/gradient/__init__.py
  pyresample/gradient/_gradient_search.c
  pyresample/gradient/_gradient_search.pyx
  pyresample/grid.py
  pyresample/image.py
  pyresample/resampler.py
  pyresample/test/__init__.py
  pyresample/test/test_geometry.py
  pyresample/test/test_gradient.py
  pyresample/test/test_kd_tree.py
  setup.py
Labels: PCW, enhancement

#225 Add smarter default radius_of_influence to XArrayResamplerNN resampling
  pyresample/geometry.py
  pyresample/kd_tree.py
  pyresample/test/test_geometry.py
  pyresample/test/test_kd_tree.py
Labels: enhancement

#245 Remove pyximports from gradient search
  pyresample/gradient/__init__.py
  pyresample/resampler.py
  pyresample/test/test_gradient.py
Labels: bug
