Repository pytroll/pyresample, pull requests merged in 2019-03, with the labels that each got.

#164 Delete unused requirements.txt file
  requirements.txt
Labels: enhancement

#167 Fix yaml area loading when projection is latlong (units degrees)
  pyresample/area_config.py
  pyresample/test/test_files/areas.yaml
  pyresample/test/test_utils.py
Labels: bug

#170 Allow create_area_def to work with incomplete proj dicts to create DynamicAreas
  pyresample/area_config.py
  pyresample/test/test_geometry.py
Labels: bug

#175 Fix dask.blockwise backwards compatibility with dask.atop
  changelog_pre1.9.1.rst
  pyresample/kd_tree.py
Labels: bug

#176 Fix typos in README and index page
  MANIFEST.in
  README.md
  docs/source/index.rst
Labels: documentation
