Repository pytroll/pyresample, pull requests merged in 2019-08, with the labels that each got.

#201 fix bug in plot example code
  docs/source/plot.rst
Labels: documentation

#196 Improve handling of EPSG codes with pyproj 2.0+
  docs/source/API.rst
  docs/source/conf.py
  docs/source/geometry_utils.rst
  pyresample/_spatial_mp.py
  pyresample/area_config.py
  pyresample/geometry.py
  pyresample/test/test_geometry.py
  pyresample/test/test_grid.py
  pyresample/test/test_spatial_mp.py
  pyresample/test/test_utils.py
  pyresample/utils/_proj4.py
Labels: bug, enhancement

#205 Exclude NaNs from Bucket Average
  pyresample/bucket/__init__.py
  pyresample/test/test_bucket.py
Labels: bug

#203 Add Numpy version limitation for Python 2
  setup.py
Labels: enhancement
