Repository pytroll/pyresample, pull requests merged in 2020-10, with the labels that each got.

#300 Refactor bilinear
  azure-pipelines.yml
  docs/source/grid.rst
  docs/source/swath.rst
  pyresample/bilinear/__init__.py
  pyresample/bilinear/xarr.py
  pyresample/image.py
  pyresample/test/test_bilinear.py
  pyresample/test/test_image.py
Labels: enhancement, refactor

#303 Add caching of bilinear information
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  docs/requirements.txt
  docs/source/swath.rst
  pyresample/bilinear/__init__.py
  pyresample/bilinear/_base.py
  pyresample/bilinear/_numpy_resampler.py
  pyresample/bilinear/xarr.py
  pyresample/test/test_bilinear.py
  setup.py
Labels: enhancement

#305 Add missing test data to package
  MANIFEST.in
  setup.py
Labels: bug
