Repository pytroll/pyresample, pull requests merged in 2020-02, with the labels that each got.

#253 Fix SwathDefinition geocentric_resolution when resolution is None
  docs/source/conf.py
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: bug, documentation

#252 Make omerc bouding box use sphere as ellps
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: bug

#254 Switch to pytest for CI and remove Python <3.4 support
  .travis.yml
  appveyor.yml
  docs/source/index.rst
  docs/source/installation.rst
  pyresample/area_config.py
  pyresample/test/__init__.py
  pyresample/test/test_bilinear.py
  pyresample/test/test_bucket.py
  pyresample/test/test_data_reduce.py
  pyresample/test/test_ewa_fornav.py
  pyresample/test/test_ewa_ll2cr.py
  pyresample/test/test_geometry.py
  pyresample/test/test_gradient.py
  pyresample/test/test_grid.py
  pyresample/test/test_image.py
  pyresample/test/test_kd_tree.py
  pyresample/test/test_plot.py
  pyresample/test/test_spatial_mp.py
  pyresample/test/test_spherical.py
  pyresample/test/test_spherical_geometry.py
  pyresample/test/test_swath.py
  pyresample/test/test_utils.py
  pyresample/test/utils.py
  pyresample/utils/_proj4.py
  pyresample/utils/_rasterio.py
  setup.py
Labels: enhancement
