Repository pytroll/pyresample, pull requests merged in 2020-05, with the labels that each got.

#264 Switch to storing CRS WKT in AreaDefinitions instead of the CRS object
  docs/source/conf.py
  docs/source/geometry_utils.rst
  pyresample/geometry.py
  pyresample/test/test_files/areas.yaml
  pyresample/test/test_geometry.py
  pyresample/test/test_grid.py
  pyresample/test/test_utils.py
  pyresample/test/utils.py
  pyresample/utils/_proj4.py
Labels: bug

#249 Fix bucket assignment
  pyresample/bucket/__init__.py
  pyresample/test/test_bucket.py
Labels: bug

#265 Fix geocentric resolution favoring one area dimension over the other
  pyresample/geometry.py
  pyresample/test/test_geometry.py
  pyresample/test/test_kd_tree.py
Labels: bug

#251 Fix bugs and use real data in the doc pages but hide code needed for …
  docs/source/conf.py
  docs/source/geo_def.rst
  docs/source/geometry_utils.rst
  docs/source/plot.rst
  docs/source/plot_cartopy_basemap.rst
  docs/source/plot_projections.rst
  pyresample/plot.py
Labels: bug, documentation

#276 Create AreaDefinition from epsg codes
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: enhancement

#275 Check area slices for correct step
  pyresample/geometry.py
  pyresample/test/test_utils.py
  pyresample/utils/__init__.py
Labels: bug

#279 Refactor API docs to document things more easily
  .stickler.yml
  docs/README.md
  docs/source/API.rst
  docs/source/api/pyresample.bilinear.rst
  docs/source/api/pyresample.bucket.rst
  docs/source/api/pyresample.ewa.rst
  docs/source/api/pyresample.gradient.rst
  docs/source/api/pyresample.rst
  docs/source/api/pyresample.utils.rst
  docs/source/index.rst
  pyresample/area_config.py
  pyresample/geo_filter.py
  pyresample/geometry.py
  pyresample/plot.py
  pyresample/spherical_geometry.py
  pyresample/test/test_geometry.py
  pyresample/test/test_utils.py
  pyresample/utils/__init__.py
  pyresample/utils/cartopy.py
  pyresample/utils/proj4.py
  pyresample/utils/rasterio.py
Labels: documentation, enhancement

#271 Create AreaDefinition from a netCDF/CF file
  azure-pipelines.yml
  docs/source/api/pyresample.utils.rst
  docs/source/geometry_utils.rst
  pyresample/area_config.py
  pyresample/geometry.py
  pyresample/test/test_geometry.py
  pyresample/test/test_utils.py
  pyresample/utils/__init__.py
  pyresample/utils/cf.py
  setup.py
Labels: enhancement

#282 Remove chunks that do not intersect target area in gradient search resampling
  .travis.yml
  appveyor.yml
  pyresample/gradient/__init__.py
  pyresample/gradient/_gradient_search.c
  pyresample/gradient/_gradient_search.pyx
  pyresample/test/test_gradient.py
  setup.cfg
  setup.py
Labels: enhancement
