Repository pytroll/pyresample, pull requests merged in 2021-11, with the labels that each got.

#388 Fix indentation on geometry utils page
  docs/source/geometry_utils.rst
Labels: documentation

#389 Fix SwathDefinition get_bbox_lonlats returning counter-clockwise coordinates
  pyresample/geometry.py
  pyresample/spherical.py
  pyresample/test/test_geometry.py
  pyresample/test/utils.py
Labels: bug

#395 Replace depracated Numpy dtypes
  pyresample/_spatial_mp.py
  pyresample/bilinear/xarr.py
  pyresample/bucket/__init__.py
  pyresample/future/resamplers/nearest.py
  pyresample/kd_tree.py
  pyresample/test/test_kd_tree.py
  setup.py
Labels: enhancement

#396 Add Python 3.9 to CI runs and use it for the experimental run
  .github/workflows/ci.yaml
Labels: enhancement

#398 Fix EWA resampling when input data is larger than the output area
  pyresample/ewa/_fornav_templates.cpp
  pyresample/ewa/dask_ewa.py
  pyresample/test/test_ewa_fornav.py
Labels: bug
