Repository pytroll/pyresample, pull requests merged in 2021-07, with the labels that each got.

#370 Fix dask ewa issues with newer versions of dask
  pyresample/ewa/dask_ewa.py
Labels: bug

#347 Add spherical geometry support for deriving total/common area coverage of several satellite overpasses
  .readthedocs.yml
  docs/environment.yml
  docs/requirements.txt
  docs/source/_static/images/2_passes_between_202001051137_and_202001051156.png
  docs/source/geo_def.rst
  docs/source/index.rst
  docs/source/spherical_geometry.rst
  pyresample/spherical.py
  pyresample/spherical_utils.py
  pyresample/test/test_spherical.py
  pyresample/test/test_spherical_utils.py
Labels: enhancement

#373 Add initial draft of a Roadmap page
  docs/source/index.rst
  docs/source/roadmap.rst
Labels: documentation
