Repository pytroll/pyresample, pull requests merged in 2021-03, with the labels that each got.

#314 Add citation information
  CITATION
  README.md
Labels: documentation

#308 Change create_areas_def to dump and set default yaml style
  docs/source/geometry_utils.rst
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: enhancement

#334 Fix wrong varname in bucket doc
  pyresample/bucket/__init__.py
Labels: documentation

#336 Switch to building cython extensions at installation time
  .github/workflows/deploy.yaml
  .gitignore
  continuous_integration/build-manylinux-wheels.sh
  docs/source/installation.rst
  pyproject.toml
  pyresample/ewa/_fornav.cpp
  pyresample/ewa/_ll2cr.c
  pyresample/gradient/_gradient_search.c
  setup.py
Labels: enhancement

#332 Require pyproj 2.2+ and remove fallbacks when CRS objects can be used
  README.md
  RELEASING.md
  pyresample/_spatial_mp.py
  pyresample/area_config.py
  pyresample/ewa/_ll2cr.pyx
  pyresample/geometry.py
  pyresample/test/test_dask_ewa.py
  pyresample/test/test_geometry.py
  pyresample/test/test_grid.py
  pyresample/test/test_utils.py
  pyresample/utils/__init__.py
  pyresample/utils/cf.py
  pyresample/utils/proj4.py
  setup.py
Labels: backwards-incompatibility, enhancement

#337 Switch docstrings to Google style
  pyresample/_spatial_mp.py
  pyresample/area_config.py
  pyresample/bilinear/__init__.py
  pyresample/boundary.py
  pyresample/data_reduce.py
  pyresample/ewa/__init__.py
  pyresample/ewa/_fornav.pyx
  pyresample/ewa/_ll2cr.pyx
  pyresample/geo_filter.py
  pyresample/geometry.py
  pyresample/grid.py
  pyresample/image.py
  pyresample/kd_tree.py
  pyresample/plot.py
  pyresample/spherical.py
  pyresample/spherical_geometry.py
  pyresample/test/test_bucket.py
  pyresample/test/test_ewa_fornav.py
  pyresample/test/test_ewa_ll2cr.py
  pyresample/test/test_geometry.py
  pyresample/test/test_kd_tree.py
  pyresample/test/test_spherical.py
  pyresample/test/test_spherical_geometry.py
  pyresample/test/test_swath.py
  pyresample/test/utils.py
  pyresample/utils/__init__.py
  pyresample/utils/cartopy.py
  pyresample/utils/proj4.py
  pyresample/version.py
  versioneer.py
Labels: documentation

#306 Add a function to join/enclose areas.
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: enhancement

#338 Add CRS option to create_area_def docs
  pyresample/area_config.py
Labels: documentation

#343 Fix EWA resampling when the result is all fill values
  pyresample/ewa/dask_ewa.py
  pyresample/test/test_dask_ewa.py
Labels: bug

#342 Fix DynamicAreaDefinition not handling lons over antimeridian
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: bug

#340 Fix get_area_slices for flipped areas
  docs/source/geometry_utils.rst
  pyresample/geometry.py
  pyresample/test/test_geometry.py
  pyresample/utils/__init__.py
Labels: bug
