Repository pytroll/pyresample, pull requests merged in 2021-12, with the labels that each got.

#401 Optimize AreaDefinition.get_proj_coords when requesting dask arrays
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: enhancement

#404 Fix dask EWA code not creating unique dask task names for different target areas
  .github/workflows/deploy.yaml
  pyresample/ewa/dask_ewa.py
  pyresample/test/test_dask_ewa.py
Labels: bug

#400 Move bilinear import to avoid unnecessary warning
  pyresample/image.py
Labels: bug

#399 Fix deprecated numpy data type usage in bilinear resampling
  pyresample/bilinear/_base.py
Labels: bug

#403 Update copyright note in documentation
  docs/source/conf.py
Labels: documentation
