Repository pytroll/pyresample, pull requests merged in 2022-07, with the labels that each got.

#435 Fix SwathDefinition causing unnecessary dask computes when used as a dict key
  .github/workflows/deploy.yaml
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: enhancement, performance

#441 Fix infinite coordinates failing to be equal
  pyresample/spherical.py
  pyresample/test/test_spherical.py
Labels: bug

#443 Remove Python 3.7 support
  .github/workflows/deploy.yaml
  continuous_integration/build-manylinux-wheels.sh
  setup.py
Labels: enhancement, backwards-incompatibility

#431 Add 'antimeridian_mode' to DynamicAreaDefinition
  pyresample/geometry.py
  pyresample/test/test_geometry.py
  pyresample/utils/proj4.py
Labels: enhancement

#446 Fix incorrect extents for DynamicAreaDefinition with 'modify_crs' antimeridian mode
  pyresample/geometry.py
  pyresample/test/test_geometry.py
Labels: bug
