Repository pytroll/pyresample, pull requests merged in 2022-06, with the labels that each got.

#341 Dask resampler and gradient search overhaul
  .readthedocs.yml
  docs/environment.yml
  docs/requirements.txt
  docs/source/api/pyresample.bilinear.rst
  docs/source/api/pyresample.ewa.rst
  docs/source/api/pyresample.future.geometry.rst
  docs/source/api/pyresample.future.resamplers.rst
  docs/source/api/pyresample.future.rst
  docs/source/api/pyresample.rst
  docs/source/api/pyresample.utils.rst
  docs/source/conf.py
  pyresample/geometry.py
  pyresample/gradient/__init__.py
  pyresample/gradient/_gradient_search.pyx
  pyresample/resampler.py
  pyresample/slicer.py
  pyresample/test/test_geometry.py
  pyresample/test/test_gradient.py
  pyresample/test/test_resample_blocks.py
  pyresample/test/test_slicer.py
Labels: enhancement

#324 Fix bilinear resampler for 1D data
  pyresample/bilinear/_base.py
  pyresample/bilinear/xarr.py
  pyresample/test/test_bilinear.py
Labels: bug

#437 Add GIL releasing to EWA cython code
  pyresample/ewa/_fornav.pyx
  pyresample/ewa/_ll2cr.pyx
Labels: performance
