Repository pytroll/pyresample, pull requests merged in 2023-12, with the labels that each got.

#563 Remove `__file__` usage in test units for `test_files` path
  pyresample/test/test_area_config.py
  pyresample/test/test_image.py
  pyresample/test/test_kd_tree.py
  pyresample/test/test_plot.py
  pyresample/test/test_swath.py
  pyresample/test/test_utils.py
  pyresample/test/utils.py
Labels: refactor

#565 Move legacy boundary to boundary directory
  pyresample/boundary/__init__.py
  pyresample/boundary/legacy_boundary.py
  pyresample/test/test_boundary/test_legacy_boundary.py
Labels: refactor

#566 Refactor area boundary sides retrieval with `_geographic_sides` and `_projection_sides` methods
  pyresample/geometry.py
  pyresample/gradient/__init__.py
  pyresample/test/test_gradient.py
Labels: refactor

#450 Area definition html representation for Jupyter notebooks
  MANIFEST.in
  pyresample/_formatting_html.py
  pyresample/area_config.py
  pyresample/geometry.py
  pyresample/static/__init__.py
  pyresample/static/css/__init__.py
  pyresample/static/css/style.css
  pyresample/static/html/__init__.py
  pyresample/static/html/icons_svg_inline.html
  pyresample/test/test_area_config.py
  pyresample/test/test_formatting.py
  pyresample/test/test_geometry/test_swath.py
Labels: enhancement, documentation

#572 Suppress PROJ4 warning about losing projection by using `to_cf()` instead of `to_dict()`
  pyresample/utils/cf.py
Labels: enhancement

#564 Refactor ``test_area`` and move boundary related tests to ``test_area_boundary``
  pyresample/geometry.py
  pyresample/test/test_geometry/conftest.py
  pyresample/test/test_geometry/test_area.py
  pyresample/test/test_geometry/test_area_boundary.py
  pyresample/test/test_geometry/test_swath.py
  pyresample/test/test_geometry/test_swath_boundary.py
Labels: refactor

#573 Switch test area fixtures to session-scoped
  pyresample/test/conftest.py
  pyresample/test/test_formatting.py
  pyresample/test/test_geometry/conftest.py
Labels: bug
