Repository pytroll/pyresample, pull requests merged in 2023-06, with the labels that each got.

#523 Fix DynamicAreaDefinition not preserving user's requested resolution
  pyresample/geometry.py
  pyresample/test/test_geometry_legacy.py
  pyresample/test/test_gradient.py
Labels: bug

#522 Handle value-less parameters in `proj4_dict_to_str`
  pyresample/test/test_utils.py
  pyresample/utils/proj4.py
Labels: enhancement, backwards-incompatibility

#516 Allow cropping non-geos areas
  pyresample/geometry.py
  pyresample/test/test_geometry/test_area.py
Labels: enhancement
