Repository pytroll/pyresample, pull requests merged in 2023-03, with the labels that each got.

#502 Add stacklevel to all pyresample warnings
  .pre-commit-config.yaml
  pyresample/area_config.py
  pyresample/bilinear/__init__.py
  pyresample/bilinear/_base.py
  pyresample/bilinear/_numpy_resampler.py
  pyresample/bilinear/xarr.py
  pyresample/boundary.py
  pyresample/future/resamplers/nearest.py
  pyresample/future/resamplers/registry.py
  pyresample/geometry.py
  pyresample/gradient/__init__.py
  pyresample/image.py
  pyresample/kd_tree.py
  pyresample/plot.py
  pyresample/spherical_geometry.py
  pyresample/test/test_geometry/test_area.py
Labels: bug

#501 Couple of small typos found in documentation.
  docs/source/swath.rst
Labels: documentation

#508 Fix gradient resampling to same area not working
  pyresample/resampler.py
  pyresample/test/test_gradient.py
  pyresample/test/test_resamplers/test_resampler.py
Labels: bug

#505 Add pre-allocation option to `get_neighbour_info` to improve performance on large raster data
  pyresample/kd_tree.py
  pyresample/test/test_utils.py
  pyresample/utils/row_appendable_array.py
Labels: enhancement, performance
