Repository pytroll/pyresample, pull requests merged in 2024-02, with the labels that each got.

#582 Fix Cython 3 and Numpy 2 compatibility
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  pyproject.toml
  pyresample/area_config.py
  pyresample/ewa/_fornav.pyx
  pyresample/ewa/_ll2cr.pyx
  pyresample/geometry.py
  pyresample/gradient/_gradient_search.pyx
  pyresample/kd_tree.py
  pyresample/version.py
  setup.py
  versioneer.py
Labels: enhancement, dependencies

#556 Add missing meta keyword arguments on all dask map_blocks calls
  pyresample/_spatial_mp.py
  pyresample/bilinear/xarr.py
  pyresample/bucket/__init__.py
  pyresample/future/resamplers/nearest.py
  pyresample/geometry.py
  pyresample/kd_tree.py
  pyresample/utils/proj4.py
Labels: bug

#583 Build wheels against numpy 2
  .github/workflows/deploy.yaml
  pyproject.toml
Labels: enhancement, dependencies

#585 Fix optimize_projection handling in YAML parsing
  pyresample/area_config.py
  pyresample/test/test_area_config.py
  pyresample/test/test_files/areas.yaml
Labels: bug

#578 Add attrs to future swath definition
  pyresample/future/geometry/swath.py
  pyresample/test/conftest.py
  pyresample/test/test_geometry/test_swath.py
Labels: enhancement

#586 Include package data
  setup.py
Labels: bug
